_BASE_: "./Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
DATASETS:
  TRAIN: ('unify_trainval_novel_1shot_seedx',)
  TEST: ('unify_test_base',)
SOLVER:

  STEPS: (400,)
  MAX_ITER: 500
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
OUTPUT_DIR: "/Path/to/Output/Dir"